export default class YourListModel {
    constructor() {
        this.data = {
            results: [
                {
                    itemID: 1,
                    title: "The mask of sanity",
                    contributor: ["Hervey M. Cleckley"],
                    description: ["No description available."],
                    date: 1941,
                    rating: 1.4,
                    image_url: ["https://covers.openlibrary.org/b/olid/OL8518405M-L.jpg"],
                    resell_price: 46.02,
                    seller: "CampusBooks",
                    tags: "general",
                },
                {
                    itemID: 2,
                    title: "Physics Textbook Part - 1 for Class - 11 - 11086",
                    contributor: ["NCERT (Author)"],
                    description: ["No description available."],
                    date: 2014,
                    rating: 2.3,
                    image_url: [
                        "https://covers.openlibrary.org/b/olid/OL27054365M-L.jpg",
                    ],
                    resell_price: 113.23,
                    seller: "BookBarn",
                    tags: "science physics mechanics",
                },
                {
                    itemID: 3,
                    title: "The united-independent compensatory code/system/concept",
                    contributor: ["Neely Fuller"],
                    description: ["No description available."],
                    date: 1984,
                    rating: 3.1,
                    image_url: [""],
                    resell_price: 110.34,
                    seller: "BookBarn",
                    tags: "general",
                },
                {
                    itemID: 4,
                    title: "Our sexuality",
                    contributor: ["Crooks, Robert, Robert L. Crooks, Karla Baur"],
                    description: ["No description available."],
                    date: 1980,
                    rating: 3.6,
                    image_url: ["https://covers.openlibrary.org/b/olid/OL3699118M-L.jpg"],
                    resell_price: 54.82,
                    seller: "ScholarTrade",
                    tags: "general",
                },
                {
                    itemID: 5,
                    title: "Macroeconomics",
                    contributor: [
                        "Campbell R. McConnell, Stanley L. Brue, Sean M. Flynn, Thomas Paul Barbiero, Sean Flynn",
                    ],
                    description: ["No description available."],
                    date: 1989,
                    rating: 2.1,
                    image_url: ["https://covers.openlibrary.org/b/olid/OL9250781M-L.jpg"],
                    resell_price: 144.26,
                    seller: "ScholarTrade",
                    tags: "business",
                },
                {
                    itemID: 6,
                    title: "Research in psychology",
                    contributor: ["C. James Goodwin"],
                    description: ["No description available."],
                    date: 1995,
                    rating: 4.5,
                    image_url: [""],
                    resell_price: 35.09,
                    seller: "CampusBooks",
                    tags: "social science behavior psychology",
                },
                {
                    itemID: 7,
                    title: "Life-span development",
                    contributor: ["John W. Santrock"],
                    description: ["No description available."],
                    date: 2005,
                    rating: 4.7,
                    image_url: [
                        "https://covers.openlibrary.org/b/olid/OL24412871M-L.jpg",
                    ],
                    resell_price: 57.92,
                    seller: "BookBarn",
                    tags: "social science behavior",
                },
                {
                    itemID: 8,
                    title: "The Humanistic Tradition",
                    contributor: ["Gloria K. Fiero"],
                    description: ["No description available."],
                    date: 1981,
                    rating: 4.5,
                    image_url: ["https://covers.openlibrary.org/b/olid/OL3427957M-L.jpg"],
                    resell_price: 52.16,
                    seller: "ScholarTrade",
                    tags: "general",
                },
                {
                    itemID: 9,
                    title: "Psychology",
                    contributor: ["Gray, Peter"],
                    description: ["No description available."],
                    date: 1991,
                    rating: 1.9,
                    image_url: ["https://covers.openlibrary.org/b/olid/OL3944042M-L.jpg"],
                    resell_price: 35.11,
                    seller: "CampusBooks",
                    tags: "social science behavior psychology",
                },
            ],
        };
    }
    getAll() {
        return this.data.results;
    }
}
